stages:
  - build
  - test

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build debian:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  before_script:
    - |
      conda config \
        --add channels defaults \
        --add channels salilab \
        --add channels conda-forge \
        --add channels tpeulen \
        --add channels tpeulen/label/nightly
    - conda install mamba boa -n base
  script:
    - echo "I am a build stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate base
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    paths:
    - bld-dir

test debian:
  stage: test
  tags:
    - linux
  image: continuumio/miniconda3:latest
  dependencies:
    - build
  before_script:
    # Address issue with OpenGL and X11 display
    # See: https://stackoverflow.com/questions/65675765/is-it-possible-to-run-x11-on-gitlab-ci
    # See: https://github.com/conda-forge/pygridgen-feedstock/issues/10
    # procps is used to grep the process by name to kill it when needed
    - apt update -y
    - apt install -y xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libgl1-mesa-glx procps
    - |
      conda config \
        --add channels defaults \
        --add channels salilab \
        --add channels conda-forge \
        --add channels tpeulen \
        --add channels tpeulen/label/nightly
    - conda install mamba -n base
  script:
    - echo "I am a test stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate base
    - conda config --add channels "file://`pwd`/bld-dir"
    - conda create -n test
    - conda activate test
    - mamba install k2dist
    # Run GUI with xvfb, as there is no X11 screen
    - |
      xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" -- k2dist &
      sleep 10
      pgrep -f k2dist | awk '{print "kill -9 " $1}' | sh
