stages:
  - build
  - deploy

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CONDA_PACKAGE: "k2dist"
  DEPLOY_VARIABLE: "nightly"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /master/
      variables:
        DEPLOY_VARIABLE: "main"  # Override globally-defined DEPLOY_VARIABLE
    - when: always               # Run the pipeline in other cases

build linux:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  before_script:
    # Issue with OpenGL and X11 display
    # See: https://stackoverflow.com/questions/65675765/is-it-possible-to-run-x11-on-gitlab-ci
    # See: https://github.com/conda-forge/pygridgen-feedstock/issues/10
    # procps is used to grep the process by name to kill it when needed
    - apt update -y
    - apt install -y xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libgl1-mesa-glx procps
  script:
    - echo "I am a build stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate
    - conda install mamba boa conda-verify -c conda-forge
    - mamba update -y -n base -c defaults --all
    - |
        conda config --add channels defaults
        conda config --add channels salilab
        conda config --add channels conda-forge
        conda config --add channels tpeulen
        conda config --add channels tpeulen/label/nightly
    - conda mambabuild conda-recipe --output-folder bld-dir
    # Test
    - conda config --add channels "file://`pwd`/bld-dir"
    - conda activate test
    - mamba install python=3.7 ${CONDA_PACKAGE}
    # Run GUI with xvfb - no X11 screen
    - |
      xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" -- k2dist &
      sleep 10
      pgrep -f k2dist | awk '{print "kill -9 " $1}' | sh
  artifacts:
    expire_in: 7 days
    paths:
      - bld-dir/

deploy linux:
  stage: deploy
  tags:
    - linux
  image: continuumio/miniconda3:latest
  dependencies:
    - build linux
  script:
    - echo "I am a depolyment stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate
    # Install conda client to upload the package
    - conda install anaconda-client
    - anaconda upload -t ${ANACONDA_API_TOKEN} -l ${DEPLOY_VARIABLE} -u ${CONDA_USER} --force bld-dir/linux-64/${CONDA_PACKAGE}*.tar.bz2"
