build debian:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  before_script:
    - export PIP_CACHE_DIR="/opt/cache/pip"
    - conda update -n base -c defaults conda
    - conda install mamba -n base -c conda-forge
    - mamba env create -f environment.yml
    - source activate k2dist
  script:
    - echo "I am a build stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - python setup.py
    - k2dist
