stages:
  - build
  - test
  - deploy

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build linux:
  stage: build
  tags:
    - linux
  image: continuumio/miniconda3:latest
  script:
    - echo "I am a build stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate
    - conda install mamba boa -c conda-forge
    - mamba update -y -n base -c defaults conda
    - |
        conda config --add channels defaults
        conda config --add channels salilab
        conda config --add channels conda-forge
        conda config --add channels tpeulen
        conda config --add channels tpeulen/label/nightly
    - conda mambabuild conda-recipe --output-folder bld-dir
  artifacts:
    paths:
    - bld-dir

test linux:
  stage: test
  tags:
    - linux
  image: continuumio/miniconda3:latest
  dependencies:
    - build linux
  before_script:
    # Issue with OpenGL and X11 display
    # See: https://stackoverflow.com/questions/65675765/is-it-possible-to-run-x11-on-gitlab-ci
    # See: https://github.com/conda-forge/pygridgen-feedstock/issues/10
    # procps is used to grep the process by name to kill it when needed
    - apt update -y
    - apt install -y xorg-dev libglu1-mesa libgl1-mesa-dev xvfb libxinerama1 libxcursor1 libgl1-mesa-glx procps
  script:
    - echo "I am a test stage job for debian, running on docker using continuumio/miniconda3:latest image"
    - source activate
    - conda install mamba boa -c conda-forge
    - mamba update -y -n base -c defaults conda
    - |
        conda config --add channels defaults
        conda config --add channels salilab
        conda config --add channels conda-forge
        conda config --add channels tpeulen
        conda config --add channels tpeulen/label/nightly
    - conda config --add channels "file://`pwd`/bld-dir"
    - conda create -n test python=3.7
    - conda activate test
    - mamba install python=3.7 k2dist
    # Run GUI with xvfb, as there is no X11 screen
    - |
      xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" -- k2dist &
      sleep 10
      pgrep -f k2dist | awk '{print "kill -9 " $1}' | sh

#deploy linux:
#  stage: deploy
#  tags:
#    - linux
#  image: continuumio/miniconda3:latest
#  dependencies:
#    - build linux
#  script:
#    - source activate
#    - conda update -y -n base -c defaults conda
#    - echo "I am a test stage job for debian, running on docker using continuumio/miniconda3:latest image"
#    - |
#        conda config --add channels defaults
#        conda config --add channels salilab
#        conda config --add channels conda-forge
#        conda config --add channels tpeulen
#        conda config --add channels tpeulen/label/nightly
#    - conda config --add channels "file://`pwd`/bld-dir"
#    - mamba install python=3.7 k2dist
#    # Run GUI with xvfb, as there is no X11 screen
#    - |
#      xvfb-run -a -s "-screen 0 1400x900x24 +extension RANDR" -- k2dist &
#      sleep 10
#      pgrep -f k2dist | awk '{print "kill -9 " $1}' | sh
