name: k2dist

channels:
  - defaults
  - tpeulen
  - tpeulen/nightly
  - salilab
  - conda-forge

dependencies:
    - python 3.7
    - numpy
    - pyyaml >=5.0.0
    - qtpy >=1.8.0
    - pyqt >=5.13.0|5.9.2.*|5.6.0.*
    - pyqtgraph >0.10.0|0.9.10
    - scikit-fluorescence >=0.0.1
    - matplotlib
    - pathlib2 # [py < 3]
