__name__ = "k2dist"
__author__ = "Thomas-Otavio Peulen"
__version__ = "0.0.1"
__copyright__ = "Copyright (C) 2021 Thomas-Otavio Peulen"
__credits__ = ["Thomas-Otavio Peulen"]
__maintainer__ = "Thomas-Otavio Peulen"
__email__ = "thomas@peulen.xyz"
__url__ = "https://gitlab.peulen.xyz/tpeulen/k2dist"
__license__ = 'GPL2.1'
__status__ = "Dev"
__description__ = """k2dist: Fluorescence spectroscopy tool to computes orientation factor (kappa2) distributions."""
__app_id__ = "F25DCFFA-1234-4643-BC4F-2C3A20495217"
LONG_DESCRIPTION = """k2dist: a tool to compute orientation factor distributions."""
help_url = 'https://gitlab.peulen.xyz/tpeulen/k2dist'
update_url = 'https://gitlab.peulen.xyz/tpeulen/k2dist'
