{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
    number: 0
    entry_points:
      {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
      {% for entry_point in entry_points -%}
      - {{ entry_point }}
      {% endfor %}
      {% endfor %}

requirements:
  host:
    - python
    - numpy
    - pyyaml
    - setuptools
  run:
    - python
    - numpy
    - pyyaml
    - qtpy
    - pyqt
    - pyqtgraph
    - matplotlib
    - numba
    - typing_extensions

test:
  imports:
    - k2dist
  commands:
    - k2dist &        # [linux or osx]

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: Kappa2 distribution calculator
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
