{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: {{ data.get('name')|lower }}
  version: {{ data.get('version')|lower }}

source:
  path: ..

build:
  number: 0
  string: np{{ CONDA_NPY }}py{{ python }}
  entry_points:
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}
requirements:
  host:
    - python {{ python }}
    - numpy
    - pyyaml
    - setuptools
  build:
    - python {{ python }}
    - numpy
    - setuptools
    - pyyaml
  run:
    - python {{ python }}
    - numpy
    - pyyaml >=5.0.0
    - qtpy >=1.8.0
    - pyqt >=5.13.0|5.9.2.*|5.6.0.*
    - pyqtgraph >0.10.0|0.9.10
    - scikit-fluorescence >=0.0.1
    - matplotlib
    - pathlib2 # [py < 3]
    - typing_extensions

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  license_file: LICENSE
  summary: Kappa2 distribution calculator
  description: |
    {{ data.get('description') }}

extra:
  recipe-maintainers:
    - tpeulen
